dry:
	rsync --dry-run -avz ./* webadmin@cmckay.xen.prgmr.com:/home/webadmin/personal_website/public/ --exclude 'Makefile'

sync: 
	rsync -avz ./* webadmin@cmckay.xen.prgmr.com:/home/webadmin/personal_website/public/ --exclude 'Makefile'

llocal:
	rsync -avz ./ /home/crmckay/Dropbox/Repos/Personal-Website/public

mlocal:
	rsync -avz ./ /Users/crmckay/Dropbox/Repos/Personal-Website/public
